/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.miniiinstabot.scraper;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Solaiman
 */
public class Scrapper extends javax.swing.JFrame {

    /**
     * Creates new form Scrapper
     */
    public Scrapper() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFrom = new javax.swing.JTextField();
        txtTo = new javax.swing.JTextField();
        btnScrap = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 140, 30));
        getContentPane().add(txtTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 140, 30));

        btnScrap.setText("SCRAP");
        btnScrap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScrapActionPerformed(evt);
            }
        });
        getContentPane().add(btnScrap, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 300, 40));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 120));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnScrapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScrapActionPerformed
        // TODO add your handling code here:
        ZipCodeScrapper scrapper = new ZipCodeScrapper(Integer.parseInt(txtFrom.getText()),Integer.parseInt(txtTo.getText()),txtFrom.getText()+"-"+txtTo.getText());

        if (scrapper.prepareList()) {
            try {
                scrapper.loadWebDriver();
                scrapper.gotoHomePage();
                scrapper.prepareSheet();
                scrapper.getZip(Integer.parseInt(txtFrom.getText()));
                scrapper.printList();
            } catch (InterruptedException ex) {
                Logger.getLogger(ZipCodeScrapper.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnScrapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scrapper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scrapper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scrapper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scrapper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Scrapper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnScrap;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtFrom;
    private javax.swing.JTextField txtTo;
    // End of variables declaration//GEN-END:variables
}
